FROM node:19-alpine3.16

RUN mkdir -p /usr/local/scope/lib && \
    mkdir -p /usr/local/scope/bin

WORKDIR /usr/local/scope/

RUN apk add bash curl

RUN npm install hot-shots

COPY node/scope-test /usr/local/scope/
COPY node/hotshot.ts /usr/local/scope/

ENV SCOPE_CRIBL_ENABLE=false

RUN ln -s /opt/appscope/bin/linux/$(uname -m)/scope /usr/local/scope/bin/scope

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]
