#!/bin/bash

ERR=0

fail() { ERR+=1; echo >&2 "fail:" $@; }

scope service --force cribl 

echo
[ -f /etc/scope/cribl/scope.yml ] || fail "missing scope.yml"
[ -f /etc/sysconfig/cribl ] || fail "missing /etc/sysconfig/cribl"
grep LD_PRELOAD /etc/sysconfig/cribl >/dev/null 2>&1 || fail "missing LD_PRELOAD in /etc/sysconfig/cribl"
grep SCOPE_HOME /etc/sysconfig/cribl >/dev/null 2>&1 || fail "missing SCOPE_HOME in /etc/sysconfig/cribl"

if [ $ERR -gt 0 ]; then
    echo "$ERR test(s) failed"
    exit $ERR
else
    echo "All test passed"
fi
