#!/bin/bash
exec /opt/test-runner/bin/python \
    /opt/test-runner/app.py \
    -t syscalls \
    -l /opt/test-runner/logs/ \
    -s /usr/local/scope/lib/libscope.so \
    --syscalls_tests_config /opt/test-runner/syscall_tests_conf.json
