#!/bin/bash
DEBUG=0  # set this to 1 to capture the EVT_FILE for each test

FAILED_TEST_LIST=""
FAILED_TEST_COUNT=0

EVT_FILE="/opt/test/log/events.log"
BINARY_MSG="Binary data detected--- message"

starttest(){
    CURRENT_TEST=$1
    echo "==============================================="
    echo "             Testing $CURRENT_TEST             "
    echo "==============================================="
    ERR=0
}

evaltest(){
    echo "             Evaluating $CURRENT_TEST"
}

endtest(){
    if [ $ERR -eq "0" ]; then
        RESULT=PASSED
    else
        RESULT=FAILED
        FAILED_TEST_LIST+=$CURRENT_TEST
        FAILED_TEST_LIST+=" "
        FAILED_TEST_COUNT=$(($FAILED_TEST_COUNT + 1))
    fi

    echo "*************** $CURRENT_TEST $RESULT ***************"
    echo ""
    echo ""

    # copy the EVT_FILE to help with debugging
    if (( $DEBUG )) || [ $RESULT == "FAILED" ]; then
        cp -f $EVT_FILE $EVT_FILE.$CURRENT_TEST
    fi

    rm -f $EVT_FILE
}

export SCOPE_PAYLOAD_ENABLE=true
export SCOPE_PAYLOAD_HEADER=true

#
# cat html (negative test)
#

starttest cat_html

ldscope cat docker/demo/nginx/html/index.html > /dev/null
evaltest

grep "$BINARY_MSG" $EVT_FILE > /dev/null
if [ $? -eq 0 ]; then
    ERR+=1
fi

endtest

#
# cat binary file
#

starttest cat_binary

ldscope cat /usr/local/scope/bin/ldscope > /dev/null
evaltest

grep "$BINARY_MSG" $EVT_FILE > /dev/null
ERR+=$?

endtest


#
# curl png
#

starttest curl_png

ldscope curl https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png --output - > /dev/null
evaltest

grep "$BINARY_MSG" $EVT_FILE > /dev/null
ERR+=$?

endtest

#
# trace log level
#

starttest trace_level_test

SCOPE_LOG_LEVEL=trace ldscope ps -ef
if [ $? -ne 0 ]; then
    ERR+=1
fi

evaltest

endtest

unset SCOPE_PAYLOAD_ENABLE
unset SCOPE_PAYLOAD_HEADER

if (( $FAILED_TEST_COUNT == 0 )); then
    echo ""
    echo ""
    echo "*************** ALL TESTS PASSED ***************"
else
    echo "*************** SOME TESTS FAILED ***************"
    echo "Failed tests: $FAILED_TEST_LIST"
    echo "Refer to these files for more info:"
    for FAILED_TEST in $FAILED_TEST_LIST; do
        echo "  $EVT_FILE.$FAILED_TEST"
    done
fi

exit ${FAILED_TEST_COUNT}
