#! /bin/bash

DEBUG=0  # set this to 1 to capture the EVT_FILE for each test

FAILED_TEST_LIST=""
FAILED_TEST_COUNT=0

EVT_FILE="/opt/test-runner/logs/events.log"

starttest(){
    CURRENT_TEST=$1
    echo "==============================================="
    echo "             Testing $CURRENT_TEST             "
    echo "==============================================="
    ERR=0
}

evaltest(){
    echo "             Evaluating $CURRENT_TEST"
}

endtest(){
    if [ $ERR -eq "0" ]; then
        RESULT=PASSED
    else
        RESULT=FAILED
        FAILED_TEST_LIST+=$CURRENT_TEST
        FAILED_TEST_LIST+=" "
        FAILED_TEST_COUNT=$(($FAILED_TEST_COUNT + 1))
    fi

    echo "*************** $CURRENT_TEST $RESULT ***************"
    echo ""
    echo ""

    # copy the EVT_FILE to help with debugging
    if (( $DEBUG )) || [ $RESULT == "FAILED" ]; then
        cp -f $EVT_FILE $EVT_FILE.$CURRENT_TEST
    fi

    rm -f $EVT_FILE
}

#
# extract on musl
#
starttest extract_musl

scope extract /opt/extract_scope
ERR+=$?

count=$(readelf -d /opt/extract_scope/libscope.so | grep 'Shared library:.*ld-linux' | wc -l)
if [ $count -ne 0 ] ; then 
    ERR+=1
fi

count=$(readelf -d /opt/extract_scope/libscope.so | grep 'Shared library:.*ld-musl' | wc -l)
if [ $count -ne 1 ] ; then 
    ERR+=1
fi

endtest

#
# ldscope patch
#
starttest patch_on_musl
cp /usr/local/scope/lib/libscope.so /opt/patch_libscope
cp /usr/local/scope/bin/ldscope /opt/patch_libscope

count=$(readelf -d /opt/patch_libscope/libscope.so | grep 'Shared library:.*ld-linux' | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

/opt/patch_libscope/ldscope -p /opt/patch_libscope/libscope.so
ERR+=$?

md5_after_first_patch=$(md5sum /opt/patch_libscope/libscope.so)

count=$(readelf -d /opt/patch_libscope/libscope.so | grep 'Shared library:.*ld-musl' | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

/opt/patch_libscope/ldscope -p /opt/patch_libscope/libscope.so
if [ $? -eq 0 ]; then
    ERR+=1
fi

md5_after_second_patch=$(md5sum /opt/patch_libscope/libscope.so)

if [ "$md5_after_first_patch" != "$md5_after_second_patch" ]; then
    ERR+=1
fi

endtest

#
# fwrite binary
#
starttest fwrite

ldscope /opt/fwrite/fwrite
ERR+=$?

sleep 0.5
count=$(grep '"source":"fs.open"' $EVT_FILE | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

count=$(grep '"source":"fs.duration"' $EVT_FILE | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

count=$(grep '"source":"fs.write"' $EVT_FILE | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

count=$(grep '"source":"fs.close"' $EVT_FILE | wc -l)
if [ $count -ne 1 ] ; then
    ERR+=1
fi

endtest


#
# tls
#
starttest tls
export SCOPE_EVENT_DEST=tcp://127.0.0.1:9109
export SCOPE_EVENT_TLS_ENABLE=true
export SCOPE_EVENT_TLS_VALIDATE_SERVER=false
export SCOPE_EVENT_TLS_CA_CERT_PATH=/usr/local/scope/cert.pm

# tcpserver receives over a tls session
cd /usr/local/scope
./tcpserver -t 9109 > $EVT_FILE &

# ldscope will send over tls session
ldscope ps -ef
retval=$?

evaltest

# Verify that ps -ef is successful
if [ $retval -ne 0 ]; then
    ERR+=1
fi

# Verify that data made it through
if ( ! grep '"sourcetype":"console"' $EVT_FILE ); then
    ERR+=1
fi

endtest



if (( $FAILED_TEST_COUNT == 0 )); then
    echo ""
    echo ""
    echo "*************** ALL TESTS PASSED ***************"
else
    echo "*************** SOME TESTS FAILED ***************"
    echo "Failed tests: $FAILED_TEST_LIST"
    echo "Refer to these files for more info:"
    for FAILED_TEST in $FAILED_TEST_LIST; do
        echo "  $EVT_FILE.$FAILED_TEST"
    done
fi

exit ${FAILED_TEST_COUNT}
