#!/bin/bash

#set -x

ERR=0
ERRORS=

URL=http://nghttp2.org/robots.txt

echo
echo ===============================================================================
echo "Starting Cribl LogStream"
openssl req -newkey rsa:2048 -nodes -keyout /tmp/appscope.key -x509 -days 365 -out /tmp/appscope.crt -subj '/C=US/ST=GA/L=Canton/O=AppScope/OU=IT/CN=appscope'
mkdir /tmp/out
/opt/cribl/bin/cribl start
sleep 5

echo
echo ===============================================================================
echo Testing HTTP/1.1
rm -rf /tmp/out/appscope:in_appscope
scope run -c tcp://localhost:10090 -- curl -Lso /dev/null --http1.1 $URL
sleep 6
if compgen -G "/tmp/out/appscope:in_appscope/CriblOut-*.json" > /dev/null; then
    echo "  PASSED?? Well, got something..."
    cat /tmp/out/appscope:in_appscope/CriblOut-*.json
    #egrep '"source" *: *"http-' /tmp/out/appscope:in_appscope/CriblOut-*.json | jq -CS . -
else
    echo "  FAILED, nothing there..."
    ERR+=1
    ERRORS="$ERRORS HTTP/1.1"
    ls -lR /tmp/out 
fi

echo
echo ===============================================================================
echo Testing HTTP/2-Prior-Knowledge
rm -rf /tmp/out/appscope:in_appscope
scope run -c tcp://localhost:10090 -- curl -Lso /dev/null --http2-prior-knowledge $URL
sleep 6
if compgen -G "/tmp/out/appscope:in_appscope/CriblOut-*.json" > /dev/null; then
    echo "  PASSED?? Well, got something..."
    cat /tmp/out/appscope:in_appscope/CriblOut-*.json
    #egrep '"source" *: *"http-' /tmp/out/appscope:in_appscope/CriblOut-*.json | jq -CS . -
else
    echo "  FAILED, nothing there..."
    ERR+=1
    ERRORS="$ERRORS HTTP/2-Prior-Knowledge"
    ls -lR /tmp/out
fi

echo
echo ===============================================================================
if [ -n "$ERRORS" ]; then
    echo >&2 "$ERR HTTP tests failed; $ERRORS"
else
    echo "All HTTP tests passed"
fi
exit $ERR

