FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install -y \
      curl \
      emacs \
      gcc \
      gdb \
      lsof \
      vim \
      wget \
    && rm -rf /var/lib/apt/lists/*

