#!/bin/bash

mkdir -p /var/log/gogen /var/log/beats

#sleep 5 && sh /sbin/loaddata.sh &

redis-server --protected-mode no &

if [ "x86_64" = "$(uname -m)" ]; then
#service mongod start
mongod --dbpath /var/lib/mongo --logpath /var/log/mongodb/mongod.log --fork
fi

exec /opt/test-runner/bin/test_protocols.sh
